const express = require('express') 
const cors = require('cors') 
const app = express() 
const routes = require('./routes/index')
require('./utils/sendContactForm').verifyMailConnection()
app.use(express.json()) 
app.use(cors())
app.use(routes)
app.listen()